// Generated by multisetgen. DO NOT EDIT!
package stringset

import "fmt"

type StringSet map[string]int

func NewStringSet() StringSet {
	return StringSet{}
}

func (m StringSet) Insert(val string) {
	m[val]++
}

func (m StringSet) Erase(val string) {
	if _, exists := m[val]; !exists {
		return
	}
	m[val]--
	if m[val] <= 0 {
		delete(m, val)
	}
}

func (m StringSet) Count(val string) int {
	return m[val]
}

func (m StringSet) String() string {
	vals := ""
	for val, count := range m {
		for i := 0; i < count; i++ {
			vals += fmt.Sprint(val) + " "
		}
	}
	return "{ " + vals + "}"
}
